name: Build and Test

on:
  push:
    branches: 
      - main
      - CI-test
  pull_request:
    branches:
      - main
      - CI-test

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up CMake
    - name: Set up CMake
      uses: lukka/get-cmake@latest

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get remove -y g++-13
        sudo apt-get install -y g++=4:13.2.0-7ubuntu1

    - name: Install nlohmann/json
      run: |
        # Clone and install nlohmann/json
        cd ${{ github.workspace }}
        git clone https://github.com/nlohmann/json.git
        cd json
        mkdir build && cd build
        cmake -DJSON_BuildTests=OFF -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_party ..
        make install
        cd ../..
  
    - name: Install uriparser
      run: |
        # Clone and install uriparser
        cd ${{ github.workspace }}
        git clone https://github.com/uriparser/uriparser
        cd uriparser
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DURIPARSER_BUILD_WCHAR_T=OFF -DURIPARSER_BUILD_TESTS=OFF -DURIPARSER_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/third_party ..
        make install
        cd ../..

    # Configure the project
    - name: Configure with CMake
      run: |
        cd ${{ github.workspace }}
        cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=${{ github.workspace }}/third_party -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DDO_OUTPUT_TESTS=OFF
          

    # Build the project
    - name: Build the project
      run: cmake --build build --target all -- -j$(nproc)

    - name: Upload dependency artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dependencies
        path: third_party

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Checkout the code (necessary to keep the source files synced)
    - name: Checkout code
      uses: actions/checkout@v3

    # Download build artifacts
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: build
    
    # Download dependency artifacts
    - name: Download dependency artifacts
      uses: actions/download-artifact@v3
      with:
        name: dependencies
        path: third_party

    # Run tests
    - name: Run tests
      run: |
        chmod +x ./build/tests
        ctest --test-dir build --output-on-failure
